main_app/urls.py
"""Defines url patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'main_app'

urlpatterns = [
    # Home page.
    path('', views.IndexView.as_view(), name='index'),

    # Show all topics.
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    path('opics/<int:topic_id>/new_entry', views.new_entry, name='new_entry'),

    # Page for editting an existence entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

unknown/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Page for administrator
    path('admin/', admin.site.urls),

    # Pages of main app
    path('', include('main_app.urls')),

    # Pages for managing users
    path('users/', include('users.urls')),
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import re_path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    # Login page.
    re_path(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout page.
    re_path(r'^logout/$', views.logout_view, name='logout'),

    # Registration page. 
    re_path(r'^register/$', views.register, name='register'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) >= 50:
            return self.text[:50] + "..."

        return self.text

users/models.py
from django.db import models

# Create your models here.

main_app/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

main_app/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

class IndexView(generic.TemplateView):
    """The home page for Learning Log."""
    template_name = 'main_app/index.html'

@login_required
def topics(request):
    """Show all topics."""
    topics_list = get_list_or_404(Topic.objects.order_by('date_added'), owner=request.user)

    context = {'topics': topics_list}

    return render(request, 'main_app/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic, and all its entries."""
    topic_obj = get_object_or_404(Topic, id=topic_id)

    if topic_obj.owner != request.user:
        raise Http404

    entries = topic_obj.entry_set.order_by('-date_added')
    context = {'topic': topic_obj, 'entries': entries}

    return render(request, 'main_app/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_one = form.save(commit=False)
            new_one.owner = request.user
            new_one.save()
            return HttpResponseRedirect(reverse('main_app:topics'))

    context = {'form': form}

    return render(request, 'main_app/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic_obj = get_object_or_404(Topic, id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_one = form.save(commit=False)
            new_one.topic = topic
            new_one.save()
            return HttpResponseRedirect(reverse('main_app:topic', args=[topic_id]))

    context = {'topic': topic_obj, 'form': form}

    return render(request, 'main_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry_obj = get_object_or_404(Entry, id=entry_id)
    topic_obj = entry_obj.topic

    if topic_obj.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry_obj)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry_obj, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_app:topic', args=[topic_obj.id]))

    context = {'entry': entry_obj, 'topic': topic_obj, 'form': form}

    return render(request, 'main_app/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('main_app:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in, and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('main_app:index'))

    context = {'form': form}

    return render(request, 'users/register.html', context)

main_app/templates/main_app/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main_app/style.css' %}">

<p>
  <a href="{% url 'main_app:index' %}">Home</a> -
  <a href="{% url 'main_app:topics' %}">Topics</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
  {% else %}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log in</a>
  {% endif %}
</p>

{% block content %}{% endblock %}

main_app/templates/main_app/edit_entry.html
{% extends "main_app/base.html" %}

{% block content %}

  <p><a href="{% url 'main_app:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Edit entry:</p>
    
  <form action="{% url 'main_app:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save</button>
  </form>

{% endblock content %}

main_app/templates/main_app/index.html
{% extends "main_app/base.html" %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're 
  learning about.</p>
{% endblock content %}

main_app/templates/main_app/new_entry.html
{% extends "main_app/base.html" %}

{% block content %}

  <p><a href="{% url 'main_app:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Add a new entry:</p>
  <form action="{% url 'main_app:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Submit</button>
  </form>
    
{% endblock content %}

main_app/templates/main_app/new_topic.html
{% extends "main_app/base.html" %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'main_app:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
  </form>
    
{% endblock content %}

main_app/templates/main_app/topic.html
{% extends 'main_app/base.html' %}

{% block content %}

  <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
  <p>
    <a href="{% url 'main_app:new_entry' topic.id %}">Add a new entry</a>
  </p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
      <p>
        <a href="{% url 'main_app:edit_entry' entry.id %}">Edit</a>
      </p>
    </li>
  {% empty %}
    <li>
      There are no entries for this topic yet.
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

main_app/templates/main_app/topics.html
{% extends "main_app/base.html" %}

{% block content %}

  <p>Topics</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'main_app:topic' topic.id %}">{{ topic }}</a>
	  </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'main_app:new_topic' %}">Add a new topic</a>

{% endblock content %}

users/templates/users/login.html
{% extends "main_app/base.html" %}

{% block content %}
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'main_app:index' %}" />
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "main_app/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Register</button>
    <input type="hidden" name="next"
      value="{% url 'main_app:index' %}" />
  </form>

{% endblock content %}